# Literature review 2023
## Research question

How existing mapping methods compare in terms of their adequacy to the needs of the Canadian data platform ?

NOTE | The following analysis uses data extracted on 2022-02-03

## Method

### First (title and abstract) inclusion criteria
- The paper propose a specific mapping method

### Second (integral text) inclusion criteria
- The mapping process is explicit (in contrast with simply presenting a tool without presenting the methodology)
- The method has been tested using an ontology with > 10 classes, 5 OP, and 5 DP

### Keywords

We extracted all papers written between 2000 and 2023 that fit the keywords:
```
(
    ontolog* OR "SPARQL"
)
AND
(
    "relational database" OR "SQL" OR "relational data"
)
AND
(
    datalake
    OR "schema matching" OR "schema mapping"
    OR "polystore"
    OR ((LAV OR GAV OR GLAV OR "Local as view" OR "Global as view") AND schema AND mapping)
    OR "Virtual Knowledge Graphs" OR VKG OR R2RML
    OR "health data exchange"
    OR "EHR interoperability" OR "electronic health record interoperability"
    OR "Ontology-Based Data Access"
    OR "semantic integration"
    OR "data integration"
    OR ETL OR "Extract-transform-load" OR ELT OR "Extract-load-transform"
)
```

### Search engines
#### https://pubmed.ncbi.nlm.nih.gov (27 results)
* (ontolog*[Title/Abstract] OR "SPARQL"[Title/Abstract]) AND ("relational database"[Title/Abstract] OR "SQL"[Title/Abstract] OR "relational data") AND (datalake[Title/Abstract] OR "schema matching"[Title/Abstract] OR "schema mapping"[Title/Abstract] OR "polystore"[Title/Abstract] OR (schema[Title/Abstract] AND mapping[Title/Abstract] AND (LAV[Title/Abstract] OR GAV[Title/Abstract] OR GLAV[Title/Abstract] OR "Local as view"[Title/Abstract] OR "Global as view"[Title/Abstract])) OR "Virtual Knowledge Graphs"[Title/Abstract] OR VKG[Title/Abstract] OR R2RML[Title/Abstract] OR "health data exchange"[Title/Abstract] OR "EHR interoperability"[Title/Abstract] OR "electronic health record interoperability"[Title/Abstract] OR "Ontology-Based Data Access"[Title/Abstract] OR "semantic integration"[Title/Abstract] OR "data integration"[Title/Abstract] OR ETL[Title/Abstract] OR "Extract-transform-load"[Title/Abstract] OR ELT[Title/Abstract] OR "Extract-load-transform"[Title/Abstract])AND (2002:2023[pdat])

#### https://www.scopus.com/ (457 results)
* Search: TITLE-ABS-KEY ( ontology  OR  "ontologies"  OR  "SPARQL" )  AND  TITLE-ABS-KEY ( "relational database"  OR  "SQL" OR "relational data")  AND  TITLE-ABS-KEY ( datalake  OR  "schema matching"  OR  "schema mapping"  OR  "polystore"  OR  ( ( lav  OR  gav  OR  glav  OR  "Local as view"  OR  "Global as view" )  AND  schema  AND  mapping )  OR  "Virtual Knowledge Graphs"  OR VKG OR  r2rml  OR  "health data exchange"  OR  "EHR interoperability"  OR  "electronic health record interoperability"  OR  "Ontology-Based Data Access"  OR  "semantic integration"  OR  "data integration"  OR  etl  OR  "Extract-transform-load" OR ELT OR "Extract-load-transform" ) AND PUBYEAR AFT 2000

#### https://ieeexplore.ieee.org/ (70 results)
* https://ieeexplore.ieee.org/search/searchresult.jsp?action=search&matchBoolean=true&queryText=((ontolog*%20OR%20%22SPARQL%22)%20AND%20(%22relational%20database%22%20OR%20%22SQL%22%20OR%20%22relational%20data%22)%20AND%20(datalake%20OR%20%22schema%20matching%22%20OR%20%22schema%20mapping%22%20OR%20%22polystore%22%20OR%20(schema%20AND%20mapping%20AND%20(LAV%20OR%20GAV%20OR%20GLAV%20OR%20%22Local%20as%20view%22%20OR%20%22Global%20as%20view%22))%20OR%20%22Virtual%20Knowledge%20Graphs%22%20OR%20VKG%20OR%20R2RML%20OR%20%22health%20data%20exchange%22%20OR%20%22EHR%20interoperability%22%20OR%20%22electronic%20health%20record%20interoperability%22%20OR%20%22Ontology-Based%20Data%20Access%22%20OR%20%22semantic%20integration%22%20OR%20%22data%20integration%22%20OR%20ETL%20OR%20%22Extract-transform-load%22%20OR%20ELT%20OR%20%22Extract-load-transform%22))&highlight=true&returnType=SEARCH&matchPubs=true&returnFacets=ALL&returnType=SEARCH&matchPubs=true&ranges=2000_2024_Year
* ((ontolog* OR "SPARQL") AND ("relational database" OR "SQL" OR "relational data") AND (datalake OR "schema matching" OR "schema mapping" OR "polystore" OR (schema AND mapping AND (LAV OR GAV OR GLAV OR "Local as view" OR "Global as view")) OR "Virtual Knowledge Graphs" OR VKG OR R2RML OR "health data exchange" OR "EHR interoperability" OR "electronic health record interoperability" OR "Ontology-Based Data Access" OR "semantic integration" OR "data integration" OR ETL OR "Extract-transform-load" OR ELT OR "Extract-load-transform"))

#### www.engineeringvillage.com (491 results)
* (ontolog* OR "SPARQL" WN KY) AND ("relational database" OR "SQL" OR "relational data" WN KY) AND (datalake OR "schema matching" OR "schema mapping" OR "polystore" OR (schema AND mapping AND (LAV OR GAV OR GLAV OR "Local as view" OR "Global as view")) OR "Virtual Knowledge Graphs" OR VKG OR R2RML OR "health data exchange" OR "EHR interoperability" OR "electronic health record interoperability" OR "Ontology-Based Data Access" OR "semantic integration" OR "data integration" OR ETL OR "Extract-transform-load" OR ELT OR "Extract-load-transform" WN KY) AND (2000-* WN YR)
* Includes duplicates between Compendex and Inspect

### Secondary filters
The present script is used to merge the results in a single corpus. Then, papers with these properties were removed:
* Written in an other language than French or English
* Title or Abstract were suggesting that the paper was not relevant for the review
* Was not available in open access nor withing the subscriptions of the Université de Sherbrooke
* The purpose of the paper was not to describe a data integration method
* Used an ad hoc method
* Used a method defined in an other paper from the selection
* Internet of Things: données massive, répétitive et redondante: approche statistiques ; Aussi, données considérées sur des formes très simples (mesures) et on fait l'annotation ontologique par la suite. Nous, on se base sur des ontologies complexes (en plus d'être sur BFO) avec des règles strictes comme obo et dolce

## References
* Silva, R., Neiva, F.: [Systematic Literature Review in Computer Science - A Practical Guide](https://www.researchgate.net/publication/320704338_Systematic_Literature_Review_in_Computer_Science_-_A_Practical_Guide). Federal University of Juiz de Fora, Brazil (2016).


## Analysis

---

### Library imports

In [1]:
import pandas
import re
import io
import os.path
import collections
import math
from itertools import chain
from orderedset import OrderedSet


### Loading the original CSV from search engines

#### Engineering Village

In [3]:
# Update the csv content, because it's generated with double quotes in columns
with open('v2022/EngineeringVillage.csv', 'r') as f:
    elsevier_original = f.read()
    elsevier_update = re.sub('(?<!^)(?<!,,)(?<!",)"+(?!,"|$)(?!,,)', r'', elsevier_original, flags=re.M)

elsevier_df = pandas.read_csv(io.StringIO(elsevier_update))
elsevier_df["Publication year"].fillna(elsevier_df["Publication date"], inplace=True)
elsevier_df["Publication year"] = elsevier_df["Publication year"].astype(str).str.extract(r'(\d{4})(?:$|(?:\.0))')

del elsevier_df["Publication date"]

elsevier_df

,Title,Accession number,Title of translation,Author,Author affiliation,Corresponding author(s),Editor,Source,Abbreviated source title,Sponsor,...,Classification code,IPC code,Treatment,Discipline,Funding details,Funding text,Open Access type(s),Database,Copyright,Data Provider
0,Datalog and its extensions for semantic web da...,12964820,NaN,"Gottlob, G. (1); Orsi, G. (1); Pieris, A. (1);...","(1) University of Oxford, Department of Comput...",NaN,NaN,Reasoning Web. Semantic Technologies for Advan...,NaN,NaN,...,C6160K Deductive databases - C7250R Informatio...,G06F9/44 - G06F15/18 - G06F17/30 - G06N5/04,Practical (PRA),Computers/Control engineering (C),NaN,NaN,NaN,Inspec,"Copyright 2012, The Institution of Engineering...",Engineering Village
1,Reasoning Web: Semantic Technologies for Intel...,20134116830441,NaN,NaN,NaN,NaN,NaN,Lecture Notes in Computer Science (including s...,Lect. Notes Comput. Sci.,Fluid Operations; Semafora; Association for Lo...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Compendex,"Compilation and indexing terms, Copyright 2022...",Engineering Village
2,Data warehouse systems: Design and implementation,20182705411054,NaN,"Vaisman, Alejandro (1); Zimányi, Esteban (2)","(1) Instituto Tecnológico de Buenos Aires, Bue...",NaN,NaN,Data Warehouse Systems: Design and Implementation,Data Wareh. Systems: Design and Implement.,NaN,...,722.4 Digital Computers and Systems - 723.3 Da...,NaN,NaN,NaN,NaN,NaN,NaN,Compendex,"Compilation and indexing terms, Copyright 2022...",Engineering Village
3,5th International Conference on Data Managemen...,20173003972077,NaN,NaN,NaN,NaN,NaN,Communications in Computer and Information Sci...,Commun. Comput. Info. Sci.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Compendex,"Compilation and indexing terms, Copyright 2022...",Engineering Village
4,Subsumption and complementation as data fusion...,20102012934748,NaN,"Bleiholder, Jens (1); Szott, Sascha (2); Hersc...","(1) Hasso-Plattner-Institut, Potsdam, Germany ...","Bleiholder, J.(jens.bleiholder@hpi.uni-potsdam...",NaN,Advances in Database Technology - EDBT 2010 - ...,Adv. Database Technol. - EDBT - Int. Conf. Ext...,NaN,...,723.2 Data Processing and Image Processing,NaN,NaN,NaN,NaN,NaN,NaN,Compendex,"Compilation and indexing terms, Copyright 2022...",Engineering Village
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549,Efficient Handling of SPARQL OPTIONAL for OBDA...,17962362,NaN,"Guohui Xiao (1); Kontchakov, R. (2); Cogrel, B...","(1) Free University of Bozen-Bolzano, KRDB Res...",NaN,NaN,arXiv,arXiv (USA),NaN,...,C6160D Relational databases - C6170K Knowledge...,G06F15/18 - G06F17/30 - G06N5/04,Practical (PRA),Computers/Control engineering (C),NaN,NaN,NaN,Inspec,"Copyright 2018, The Institution of Engineering...",Engineering Village
550,Formalisation and experiences of R2RML-based S...,20144700213629,NaN,"Priyatna, Freddy (1); Corcho, Oscar (1); Seque...","(1) Ontology Engineering Group, Facultad de In...","Priyatna, Freddy",NaN,WWW 2014 - Proceedings of the 23rd Internation...,WWW - Proc. Int. Conf. World Wide Web,et al.; Google; IW3C2; Microsoft; NAVER; SK pl...,...,405.3 Surveying - 723.3 Database Systems,NaN,NaN,NaN,NaN,NaN,"All Open Access, Green",Compendex,"Compilation and indexing terms, Copyright 2022...",Engineering Village
551,Efficient duplicate elimination in SPARQL to S...,20184706124454,NaN,"Bilidas, Dimitris (1); Koubarakis, Manolis (1)",(1) National and Kapodistrian University of At...,NaN,NaN,CEUR Workshop Proceedings,CEUR Workshop Proc.,NaN,...,"723 Computer Software, Data Handling and Appli...",NaN,NaN,NaN,NaN,NaN,NaN,Compendex,"Compilation and indexing terms, Copyright 2022...",Engineering Village
552,Efficient Ontology-Based Data Integration with...,17811548,NaN,"Guohui Xiao (1); Hovland, D. (2); Bilidas, D. ...","(1) Free-University of Bozen-Bolzano, Faculty ...",NaN,NaN,The Semantic Web. 15th International Conferenc...,NaN,NaN,...,C6130 Data handling techniques - C6160D Relati...,G06F7/00 - G06F15/18 - G06F17/30 - G06N5/04,Practical (PRA),Computers/Control engineering (C),NaN,NaN,NaN,Inspec,"Copyright 2018, The Institution of Engineering...",Engineering Village
553,A framework for analysis of ontology-based dat...,16373466,NaN,"Konys, A. (1)",(1) West Pomeranian University of Technology i...,NaN,NaN,Computational Collective Intelligence. 8th Int...,NaN,NaN,...,C6160D Relational databases - C6170K Knowledge...,G06F15/18 - G06F17/30 - G06N5/04,Practical (PRA),Computers/Control engineering (C),NaN,NaN,NaN,Inspec,"Copyright 2016, The Institution of Engineering...",Engineering Village

#### IEEE Explore

In [4]:
ieee_df = pandas.read_csv("v2022/ieeexplore.csv")
ieee_df

,Document Title,Authors,Author Affiliations,Publication Title,Date Added To Xplore,Publication Year,Volume,Issue,Start Page,End Page,...,Mesh_Terms,Article Citation Count,Patent Citation Count,Reference Count,License,Online Date,Issue Date,Meeting Date,Publisher,Document Identifier
0,Ontology-Based Data Access and Visualization o...,K. Bereta; G. Stamoulis; M. Koubarakis,National and Kapodistrian University of Athens...,IGARSS 2018 - 2018 IEEE International Geoscien...,4 Nov 2018,2018,NaN,NaN,407,410,...,NaN,1.0,NaN,7.0,NaN,4 Nov 2018,NaN,NaN,IEEE,IEEE Conferences
1,Query Transformation in Ontology-Based Relatio...,J. Wang; Y. Zhang; Z. Miao; J. Lu,"Inst. of Command Autom., PLA Univ. of Sci. & T...",2010 Asia-Pacific Conference on Wearable Compu...,7 Jun 2010,2010,NaN,NaN,303,306,...,NaN,3.0,NaN,12.0,NaN,7 Jun 2010,NaN,NaN,IEEE,IEEE Conferences
2,Semantic Integration of Relational Data Using ...,J. Wang; Z. Miao; Y. Zhang; J. Lu,"Inst. of Command Autom., PLA Univ. of Sci. & T...",2008 Second International Symposium on Intelli...,6 Jan 2009,2008,1.0,NaN,422,426,...,NaN,3.0,2.0,13.0,NaN,6 Jan 2009,NaN,NaN,IEEE,IEEE Conferences
3,Querying Heterogeneous Relational Database usi...,J. Wang; Z. Miao; Y. Zhang; B. Zhou,"Inst. of Command Autom., PLA Univ. of Sci. & T...",2009 Eighth IEEE/ACIS International Conference...,25 Aug 2009,2009,NaN,NaN,475,480,...,NaN,5.0,NaN,14.0,NaN,25 Aug 2009,NaN,NaN,IEEE,IEEE Conferences
4,Query processing for heterogeneous relational ...,J. Wang; Y. Zhang; J. Lu; Zhuang Miao; Bo Zhou,"Institute of Command Automation, PLA Universit...",2010 International Conference on Intelligent C...,3 Dec 2010,2010,NaN,NaN,777,781,...,NaN,2.0,NaN,16.0,NaN,3 Dec 2010,NaN,NaN,IEEE,IEEE Conferences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,Integration of heterogeneous relational databa...,M. A. Ismail; M. Yaacob; S. A. Kareem,"Faculty of CS & IT University of Malaya, 50603...",2008 International Symposium on Information Te...,26 Sep 2008,2008,3.0,NaN,1,7,...,NaN,NaN,1.0,18.0,NaN,26 Sep 2008,NaN,NaN,IEEE,IEEE Conferences
66,A linked data graph approach to integration of...,S. A. C. Bukhari; J. Mandell; S. H. Kleinstein...,Lesley H. & William L. Collins College of Prof...,2019 IEEE International Conference on Bioinfor...,6 Feb 2020,2019,NaN,NaN,1742,1749,...,NaN,NaN,NaN,17.0,NaN,6 Feb 2020,NaN,NaN,IEEE,IEEE Conferences
67,Mapping Between Data Sources on the Web,G. H. L. Fletcher; C. M. Wyss,Computer Science Department Indiana University...,International Workshop on Challenges in Web In...,12 Dec 2005,2005,NaN,NaN,173,178,...,NaN,4.0,NaN,26.0,NaN,12 Dec 2005,NaN,NaN,IEEE,IEEE Conferences
68,Datalog and Logic Databases,S. Greco; C. Molinaro,University of Calabria (Italy).; University of...,Datalog and Logic Databases,NaN,2015,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9 Dec 2015,NaN,NaN,Morgan & Claypool,Morgan and Claypool eBooks
69,Table of contents,NaN,NaN,2016 6th International Conference on IT Conver...,10 Nov 2016,2016,NaN,NaN,1,5,...,NaN,NaN,NaN,NaN,NaN,10 Nov 2016,NaN,NaN,IEEE,IEEE Conferences

#### PubMed

In [5]:
pubmed_df = pandas.read_csv("v2022/pubmed.csv")
pubmed_df

,PMID,Title,Authors,Citation,First Author,Journal/Book,Publication Year,Create Date,PMCID,NIHMS ID,DOI
0,34707915,A linked data graph approach to integration of...,"Bukhari SAC, Mandell J, Kleinstein SH, Cheung KH.",Proceedings (IEEE Int Conf Bioinformatics Biom...,Bukhari SAC,Proceedings (IEEE Int Conf Bioinformatics Biomed),2019,2021/10/28,PMC8547546,NIHMS1650506,10.1109/bibm47256.2019.8982986
1,28982381,Querying clinical data in HL7 RIM based relati...,"Priyatna F, Alonso-Calvo R, Paraiso-Medina S, ...",J Biomed Semantics. 2017 Oct 5;8(1):49. doi: 1...,Priyatna F,J Biomed Semantics,2017,2017/10/07,PMC5629785,NaN,10.1186/s13326-017-0155-8
2,34433410,LinkedImm: a linked data graph database for in...,"Bukhari SAC, Pawar S, Mandell J, Kleinstein SH...",BMC Bioinformatics. 2021 Aug 25;22(Suppl 9):10...,Bukhari SAC,BMC Bioinformatics,2021,2021/08/26,PMC8385794,NaN,10.1186/s12859-021-04031-9
3,28423769,Linked Data Applications Through Ontology Base...,"Kock-Schoppenhauer AK, Kamann C, Ulrich H, Duh...",Stud Health Technol Inform. 2017;235:131-135.,Kock-Schoppenhauer AK,Stud Health Technol Inform,2017,2017/04/21,NaN,NaN,NaN
4,31697362,Enabling semantic queries across federated bio...,"Sima AC, Mendes de Farias T, Zbinden E, Anisim...",Database (Oxford). 2019 Jan 1;2019:baz106. doi...,Sima AC,Database (Oxford),2019,2019/11/08,PMC6836710,NaN,10.1093/database/baz106
5,25588043,Ontology-based data integration between clinic...,"Mate S, Köpcke F, Toddenroth D, Martin M, Prok...",PLoS One. 2015 Jan 14;10(1):e0116656. doi: 10....,Mate S,PLoS One,2015,2015/01/15,PMC4294641,NaN,10.1371/journal.pone.0116656
6,23742129,Computational framework to support integration...,"Miyoshi NS, Pinheiro DG, Silva WA Jr, Felipe JC.",BMC Bioinformatics. 2013 Jun 6;14:180. doi: 10...,Miyoshi NS,BMC Bioinformatics,2013,2013/06/08,PMC3688149,NaN,10.1186/1471-2105-14-180
7,32647404,"""Just-in-time"" generation of datasets by consi...","Debruyne C, Pandit HJ, Lewis D, O'Sullivan D.",Knowl Inf Syst. 2020;62(9):3615-3640. doi: 10....,Debruyne C,Knowl Inf Syst,2020,2020/07/11,PMC7327958,NaN,10.1007/s10115-020-01468-x
8,19796394,A journey to Semantic Web query federation in ...,"Cheung KH, Frost HR, Marshall MS, Prud'hommeau...",BMC Bioinformatics. 2009 Oct 1;10 Suppl 10(Sup...,Cheung KH,BMC Bioinformatics,2009,2009/10/03,PMC2755818,NaN,10.1186/1471-2105-10-S10-S10
9,27605099,OntoBrowser: a collaborative tool for curation...,"Ravagli C, Pognan F, Marc P.",Bioinformatics. 2017 Jan 1;33(1):148-149. doi:...,Ravagli C,Bioinformatics,2017,2016/09/09,PMC5408772,NaN,10.1093/bioinformatics/btw579
10,31592524,"Leaf: an open-source, model-agnostic, data-dri...","Dobbins NJ, Spital CH, Black RA, Morrison JM, ...",J Am Med Inform Assoc. 2020 Jan 1;27(1):109-11...,Dobbins NJ,J Am Med Inform Assoc,2020,2019/10/09,PMC6913227,NaN,10.1093/jamia/ocz165
11,23616864,Unlocking Data for Clinical Research - The Ger...,"Ganslandt T, Mate S, Helbing K, Sax U, Prokosc...",Appl Clin Inform. 2011 Mar 30;2(1):116-27. doi...,Ganslandt T,Appl Clin Inform,2011,2013/04/26,PMC3631913,NaN,10.4338/ACI-2010-09-CR-0051
12,22163378,Using ontology databases for scalable query an...,"Lependu P, Dou D.",J Intell Inf Syst. 2011 Oct;37(2):217-244. doi...,Lependu P,J Intell Inf Syst,2011,2011/12/14,PMC3230227,NIHMS280528,10.1007/s10844-010-0133-4
13,26534843,Integrated Data Repository Toolkit (IDRT). A S...,"Bauer CR, Ganslandt T, Baum B, Christoph J, En...",Methods Inf Med. 2016;55(2):125-35. doi: 10.34...,Bauer CR,Methods Inf Med,2016,2015/11/05,NaN,NaN,10.3414/ME15-01-0082
14,14668226,SEMEDA: ontology based semantic integration of...,"Köhler J, Philippi S, Lange M.",Bioinformatics. 2003 Dec 12;19(18):2420-7. doi...,Köhler J,Bioinformatics,2003,2003/12/12,NaN,NaN,10.1093/bioinformatics/btg340
15,18789876,Knowledge-data integration for temporal reason...,"O'Connor MJ, Shankar RD, Parrish DB, Das AK.",Int J Med Inform. 2009 Apr;78 Suppl 1:S77-85. ...,O'Connor MJ,Int J Med Inform,2009,2008/09/16,NaN,NaN,10.1016/j.ijmedinf.2008.07.013
16,12520030,iProClass: an integrated database of protein f...,"Huang H, Barker WC, Chen Y, Wu CH.",Nucleic Acids Res. 2003 Jan 1;31(1):390-2. doi...,Huang H,Nucleic Acids Res,2003,2003/01/10,PMC165491,NaN,10.1093/nar/gkg044
17,23244467,"COEUS: ""semantic web in a box"" for biomedical ...","Lopes P, Oliveira JL.",J Biomed Semantics. 2012 Dec 17;3(1):11. doi: ...,Lopes P,J Biomed Semantics,2012,2012/12/19,PMC3554586,NaN,10.1186/2041-1480-3-11
18,12542408,The semantic metadatabase (SEMEDA): ontology b...,"Köhler J, Schulze-Kremer S.",In Silico Biol. 2002;2(3):219-31.,Köhler J,In Silico Biol,2002,2003/01/25,NaN,NaN,NaN
19,17238664,Ontology-driven mapping of temporal data in bi...,"Narayanan PS, O'Connor MJ, Das AK.",AMIA Annu Symp Proc. 2006;2006:1045.,Narayanan PS,AMIA Annu Symp Proc,2006,2007/01/24,PMC1839378,NaN,NaN
20,15853268,Evolving from standard vocabularies to formal ...,"Burgun A, Golbreich C, Jacquelinet C.",Stud Health Technol Inform. 2004;102:132-44.,Burgun A,Stud Health Technol Inform,2004,2005/04/28,NaN,NaN,NaN
21,12066842,A database system for the analysis of biochemi...,"Rojas I, Bernardi L, Ratsch E, Kania R, Wittig...",In Silico Biol. 2002;2(2):75-86.,Rojas I,In Silico Biol,2002,2002/06/18,NaN,NaN,NaN
22,18048193,A case study of integrating protein interactio...,"Dhanapalan L, Chen JY.",Int J Bioinform Res Appl. 2007;3(3):286-302. d...,Dhanapalan L,Int J Bioinform Res Appl,2007,2007/12/01,NaN,NaN,10.1504/IJBRA.2007.015004

#### Scopus

In [6]:
scopus_df = pandas.read_csv("v2022/scopus.csv")
scopus_df

,Authors,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,Page end,...,ISBN,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID
0,"Mansfield M., Tamma V., Goddard P., Coenen F.",57221937144;6603177973;56896863400;7004902559;,Capturing Expert Knowledge for Building Enterp...,2021,K-CAP 2021 - Proceedings of the 11th Knowledge...,NaN,NaN,NaN,129,136,...,9781450384575,NaN,NaN,English,K-CAP - Proc. Knowl. Capture Conf.,Conference Paper,Final,NaN,Scopus,2-s2.0-85120875085
1,"Ding L., Xiao G., Pano A., Stadler C., Calvane...",56001881400;57205067739;57292585500;3670527530...,Towards the next generation of the LinkedGeoDa...,2021,Journal of Web Semantics,71,NaN,100662,NaN,NaN,...,NaN,NaN,NaN,English,J. Web Semant.,Article,Final,"All Open Access, Hybrid Gold, Green",Scopus,2-s2.0-85116937615
2,"Bukhari S.A.C., Pawar S., Mandell J., Kleinste...",57196354764;56147786800;56385239900;6506423505...,LinkedImm: a linked data graph database for in...,2021,BMC Bioinformatics,22,NaN,105,NaN,NaN,...,NaN,BBMIC,34433410.0,English,BMC Bioinform.,Article,Final,"All Open Access, Gold, Green",Scopus,2-s2.0-85113392151
3,"Hao X., Ji Z., Li X., Yin L., Liu L., Sun M., ...",57225151749;12781410600;56514323100;5722513772...,Construction and application of a knowledge graph,2021,Remote Sensing,13,13,2511,NaN,NaN,...,NaN,NaN,NaN,English,Remote Sens.,Article,Final,"All Open Access, Gold",Scopus,2-s2.0-85109349710
4,"Bilidas D., Koubarakis M.",24490671300;55872674100;,Handling redundant processing in OBDA query ex...,2021,Journal of Web Semantics,68,NaN,100639,NaN,NaN,...,NaN,NaN,NaN,English,J. Web Semant.,Article,Final,NaN,Scopus,2-s2.0-85102969437
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,"Christophides V., Karvounarakis G., Koffina I....",6603617540;56009803700;13404731200;22334261500...,The ICS-FORTH SWIM: A powerful semantic web in...,2003,Proceedings of the 1st International Conferenc...,NaN,NaN,NaN,365,377,...,NaN,NaN,NaN,English,"Proc. Int. Conf. Semant. Web Databases, SWDB",Conference Paper,Final,NaN,Scopus,2-s2.0-84891466649
420,"Bonatti P., Deng Y., Subrahmanian V.S.",36762897500;57197040025;7006050903;,An ontology-extended relational algebra,2003,Proceedings of the 2003 IEEE International Con...,NaN,NaN,1251413,192,199,...,0780382420; 9780780382428,NaN,NaN,English,"Proc. IEEE Int. Conf. Inf. Reuse Integr., IRI",Conference Paper,Final,NaN,Scopus,2-s2.0-51849127107
421,"Necib C.B., Freytag J.-C.",8914773900;7004634575;,Ontology based query processing in database ma...,2003,Lecture Notes in Computer Science (including s...,2888,NaN,NaN,839,857,...,9783540399643,NaN,NaN,English,Lect. Notes Comput. Sci.,Article,Final,NaN,Scopus,2-s2.0-0242628829
422,"Deray T., Verheyden P.",6504386198;8539635200;,Towards a semantic integration of medical rela...,2003,Lecture Notes in Computer Science (including s...,2889,NaN,NaN,137,150,...,9783540204947,NaN,NaN,English,Lect. Notes Comput. Sci.,Article,Final,NaN,Scopus,2-s2.0-0242628320
423,"Huang H., Barker W.C., Chen Y., Wu C.H.",7405610992;7201833311;8084701500;8084702300;,iProClass: An integrated database of protein f...,2003,Nucleic Acids Research,31,1,NaN,390,392,...,NaN,NARHA,12520030.0,English,Nucleic Acids Res.,Review,Final,"All Open Access, Bronze, Green",Scopus,2-s2.0-0037252761

### Uniformize the sources

In [6]:
class Columns:
    def __init__(self):
        self.columns = []
        self.elsevier = {}
        self.ieee = {}
        self.pubmed = {}
        self.scopus = {}
        self.defaults = {}

    def add(self, common, elsevier, ieee, pubmed, scopus, default):
        self.columns.append(common)
        self.elsevier[elsevier] = common
        self.ieee[ieee] = common
        self.pubmed[pubmed] = common
        self.scopus[scopus] = common
        self.defaults[common] = default


columns = Columns()
columns.add(common="Title", elsevier="Title", ieee="Document Title", pubmed="Title", scopus="Title", default="NA")
columns.add(common="Authors", elsevier="Author", ieee="Authors", pubmed="Authors", scopus="Authors", default="NA")
columns.add(common="Source", elsevier="Source", ieee="Publication Title", pubmed="", scopus="", default="NA")
columns.add(common="Year", elsevier="Publication year", ieee="Publication year", pubmed="Publication year",
            scopus="Year", default="NA")
columns.add(common="Language", elsevier="Language", ieee="", pubmed="", scopus="", default="English")
columns.add(common="DOI", elsevier="DOI", ieee="DOI", pubmed="DOI", scopus="DOI", default="NA")
columns.add(common="Abstract", elsevier="Abstract", ieee="Abstract", pubmed="", scopus="", default="NA")

index = "Title"

elsevier_df.rename(columns=columns.elsevier, inplace=True)
ieee_df.rename(columns=columns.ieee, inplace=True)
pubmed_df.rename(columns=columns.pubmed, inplace=True)
scopus_df.rename(columns=columns.scopus, inplace=True)

sources_df = []
for df in [elsevier_df, ieee_df, pubmed_df, scopus_df]:
    for col in columns.columns:
        if not col in df:
            df[col] = columns.defaults[col]
    sources_df.append(df)

combined_df = pandas.concat(sources_df)[columns.columns]
combined_df = combined_df[combined_df.Language.isin(["English", "French"])]

combined_df = combined_df.drop_duplicates(['Title']).drop_duplicates(['Abstract']).drop_duplicates(['DOI'])

combined_df.set_index(index)
combined_df.to_csv("combined.csv", index=False)

combined_df

,Title,Authors,Source,Year,Language,DOI,Abstract
0,Datalog and its extensions for semantic web da...,"Gottlob, G. (1); Orsi, G. (1); Pieris, A. (1);...",Reasoning Web. Semantic Technologies for Advan...,2012,English,10.1007/978-3-642-33158-9_2,"Since the early 70s, data management played a ..."
1,Reasoning Web: Semantic Technologies for Intel...,NaN,Lecture Notes in Computer Science (including s...,2013,English,NaN,The proceedings contain 7 papers. The topics d...
2,Data warehouse systems: Design and implementation,"Vaisman, Alejandro (1); Zimányi, Esteban (2)",Data Warehouse Systems: Design and Implementation,2014,English,10.1007/978-3-642-54655-6,"With this textbook, Vaisman and Zimányi delive..."
3,5th International Conference on Data Managemen...,NaN,Communications in Computer and Information Sci...,2017,English,10.1007/978-3-319-62911-7_1,The proceedings contain 9 papers. The special ...
4,Subsumption and complementation as data fusion...,"Bleiholder, Jens (1); Szott, Sascha (2); Hersc...",Advances in Database Technology - EDBT 2010 - ...,2010,English,10.1145/1739041.1739103,The goal of data fusion is to combine several ...
...,...,...,...,...,...,...,...
394,On the decidability and finite controllability...,Rosati R.,Scopus,2006,English,10.1145/1142351.1142404,In this paper we study queries over relational...
407,DartGrid III: A semantic grid toolkit for data...,"Chen H., Wu Z.",Scopus,2005,English,10.1109/SKG.2005.60,A toolkit called DartGrid1 using technologies ...
415,SEMEDA: Ontology based semantic integration of...,"Köhler J., Philippi S., Lange M.",Scopus,2003,English,10.1093/bioinformatics/btg340,Motivation: Many molecular biological database...
416,SRS. An integration platform for databanks and...,"Etzold T., Harris H., Beaulah S.",Scopus,2003,English,10.1016/B978-155860829-0/50007-3,The sequence retrieval system (SRS) approach t...
423,iProClass: An integrated database of protein f...,"Huang H., Barker W.C., Chen Y., Wu C.H.",Scopus,2003,English,10.1093/nar/gkg044,"The iProClass database provides comprehensive,..."

### Generate the file that will be used to record the selection

In [4]:
selection_criterias = ["Not Available", "Ad Hoc", "Unrelated (Title)", "Unrelated (Abstract)", "Unrelated (First read)",
                       "Small or informal ontologies", "Proceedings", "Survey", "Kept After 2nd Filter", "Specific field",
                       "Based on", "Comments"]
selection_template_df = pandas.read_csv("selection.csv") if os.path.isfile("selection.csv") else pandas.read_csv("combined.csv")
selection_template_df.set_index("Title")

for criteria in selection_criterias:
    if not criteria in selection_template_df:
        selection_template_df.insert(len(selection_template_df.columns), criteria, "")

selection_template_df.to_csv("selection_template.csv", index=False)

#### Read the selection annotation for statistics
The selection.csv file is extracted from DataOrganizer and contains the classification annotations.

In [2]:
selection_df = pandas.read_csv("v2022/selection.csv")
statistics = ""

selection_criterias = ["Not Available", "Ad Hoc", "Unrelated (Title)", "Unrelated (Abstract)", "Unrelated (First read)",
                       "Small or informal ontologies", "Proceedings", "Survey", "Kept After 2nd Filter", "Specific field",
                       "Based on", "Comments"]

for criteria in selection_criterias:
    statistics += criteria + ": \n"
    for value in selection_df[criteria].unique().tolist():
        if type(value) == float and math.isnan(value) :
            statistics += f'\t ND -> {len(selection_df[selection_df[criteria].isna()])}\n'
        else:
            statistics += f'\t {value} -> {len(selection_df[selection_df[criteria] == value])}\n'

print(statistics)

Not Available:
	 ND -> 302
	 1.0 -> 39
Ad Hoc:
	 ND -> 325
	 1.0 -> 16
Unrelated (Title):
	 1.0 -> 64
	 ND -> 277
Unrelated (Abstract):
	 ND -> 237
	 1.0 -> 104
Unrelated (First read):
	 ND -> 323
	 1.0 -> 18
Small or informal ontologies:
	 ND -> 330
	 1.0 -> 11
Proceedings:
	 ND -> 339
	 1.0 -> 2
Survey:
	 ND -> 329
	 1.0 -> 12
Kept After 2nd Filter:
	 ND -> 327
	 1.0 -> 14
Specific field:
	 ND -> 323
	 Geospatial data -> 16
	 IoT -> 2
Based on:
	 ND -> 292
	 Ontop -> 36
	 Morph/MIRROR -> 4
	 Pinkel -> 1
	 10.1007/978-3-319-11964-9 -> 1
	 Ultrawrap -> 2
	 Wang -> 3
	 R2BA -> 1
	 Duplicates of RODI -> 1
Comments:
	 ND -> 293
	 Very interesting approach of an algorithm to semi-automatically find simple correspondances between an ontology and a relational database. However, the author doesn’t detail the mapping mechanisms, that are the subject of this review. -> 1
	 Example of what data integration methods can achieve -> 1
	 Creating an ontology based on a relational datasource is interesting. However, we would still need a mean for the ontology alignments. While it would be a promising avenue, it would result in the usage of high-complexity algorithms (most of theses algorithms are exp-time) or probabilistic methods that would not be sufficient in the context of biomedical queries.  -> 1
	 Very interesting and promising for the ATE, but doesn’t describes a mapping process.  -> 1
	 Ontop implementation at Siemens -> 1
	 The model derived from the ontologies in this paper are really simple. Therefore, the method doesn’t seem to be relevant for the purpose of this review.   -> 1
	 Usage of CSV as an intermediary doesn’t fit the basic requirements of this review -> 1
	 It’s actually related, but it seems to be more of an interesting critic of the approach. -> 1
	 Interesting idea, but doesn’t fit the purpose of accessing sources data using a pre-mediated schema based on philosophical ontologies. -> 1
	 Definition of an ontology for the Semantic Reconciliation in Humanitarian Aid and usage of COMA++ for the mapping definition. -> 1
	 Extraction of an ontology per source -> 1
	 One ontology per source, mediated. -> 1
	 One ontology per sources -> 1
	 OBDA critic -> 1
	 Could be worth to buy access -> 1
	 Describes a mean to generate an Ontological A-Box from a relational database using a direct mapping approach. -> 1
	 This method might be give interesting ideas for the ATE -> 1
	 Query rewriting algorithm, without explicitly defining the mapping process. -> 1
	 Excellent idea for a data warehouse perpective, however the method doesn’t seems to support mediation  -> 1
	 Nice optimisation for ODBA -> 1
	 Only an abstract -> 1
	 Very interesting -> 1
	 A very promising approach. However, it’s based on a mapping style that uses a mediated ontology rather that a philosophical ontology -> 1
	 Describes only the proposition algorithm, not the data integration process itself. -> 1
	 Interesting demo of the I2B2 capabilities -> 1
	 Will be useful for the ATE -> 1
	 This paper is really promising, however the p2p approach	is not really applicable to the biomedical field, because of the need of a binary accessibility relation between peers, and because direct mapping would not be appropriate in this case. Also, we can aim to stronger assertion then intensional equivalence, because the network is not composed of highly dynamic computers.  -> 1
	 This paper is indeed interesting for the conceptual framework it describe (ci K@D, K⇔D, D⋈K, D@K). However, it doesn’t describe a mean to access existing data using an ontology, it describes a mean to develop a new database based on ontology/conceptual model. -> 1
	 Is not a method, but the paper will be used to comment odba methods in general -> 1
	 Not based on ontology or other knowledge based technologies -> 1
	 Translates ER schemas into semantically equivalent OWL Lite ontologies. -> 1
	 This method is an extension to the Direct Mapping approach. Therefore, it doesn’t fit the basic criteria of this review.  -> 1
	 Duplicate -> 1
	 Very interesting, however it’s more about the description of the similarities and differences of the two model rather than a mapping between the two models. -> 1
	 Seems to have a lot of content about performance -> 1
	 Similar to direct mapping, hence not directly related to our problem. -> 1
	 Might be interesting for the ATE -> 1
	 Not directly related to our problem, but seems to be an interesting approach for the step of query rewriting ! -> 1
	 This paper is about direct mapping, which is not the subject of this review. -> 1
	 Not directly related, but seems to be an interesting point of view -> 1
	 Interesting query optimisation -> 1
	 This method would really be interesting for the ATE. -> 1
	 Seems interesting for the ATE -> 1
	 Describes a direct mapping approach, that is not the problem of this review. -> 1
	 Interesting matching technique, also based on the database documentation.  -> 1
	 Their ontological representation of data source is direct mapping, hence not the problem of this review. -> 1
	 Might be a useful optional feature of a mapping software.  -> 1
	 Doesn’t describe the mapping process itself, only the visualisation. -> 1

#### Articles dont il faut lire l'abstract et décider si on demande le texte complet

In [14]:
selection_df[selection_df["Not Available"].notna()]

,Title,Authors,Source,Year,Language,Doi,Abstract,Not Available,Ad Hoc,Unrelated (Title),Unrelated (Abstract),Unrelated (First read),Small or informal ontologies,Proceedings,Survey,Kept After 2nd Filter,Specific field,Based on,Comments,Worth contacting the author
2,A building method of virtual knowledge base ba...,"Li, Huayu (1); Zhang, Xiaoming (2)",Advances in Intelligent and Soft Computing,2011.0,English,10.1007/978-3-642-25661-5_73,For distributed relational data sources in oil...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,A FCA-based approach to data integration in th...,"Liu, Yong (1); Li, Xueqing (2)",Lecture Notes in Electrical Engineering,2014.0,English,10.1007/978-94-007-7618-0_74,The relational database is the most widely use...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,A framework exchanging data from database reso...,Abbasi A.A.,Scopus,2016.0,English,10.3923/jeasci.2016.1568.1574,"Now a days, databases offer the best technique...",1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,A framework for analysis of ontology-based dat...,"Konys, Agnieszka (1)",Lecture Notes in Computer Science (including s...,2016.0,English,10.1007/978-3-319-45246-3_38,In last decade the terms related to Semantic W...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,A Language for Ontology-based Metamodeling Sys...,"Jean, S. (1); Aït-Ameur, Y. (1); Pierra, G. (1)",Advances in Databases and Information Systems....,2010.0,English,10.1007/978-3-642-15576-5_20,"Nowadays, metamodeling techniques and ontologi...",1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,A Semantic-Based EMRs Integration Framework fo...,Huili Jiang (1); Zili Zhang (1); Li Tao (1),"Knowledge Science, Engineering and Management....",2014.0,English,10.1007/978-3-319-12096-6_34,Discovering latent information from Electronic...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,A survey of approaches to representing SPARQL ...,"M., Chaloupka; M., Neaský",Lecture Notes in Computer Science (including s...,2017.0,English,10.1007/978-3-319-69459-7_21,RDF is a universal data model for publishing s...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,A systematic mapping study of database resourc...,"Abbasi A.A., Kulathuramaiyer N.",Scopus,2016.0,English,10.3923/ajit.2016.730.737,This study aims at proposing transformation te...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Accessing relational data on the web with Spar...,"Unbehauen, Jörg (1); Stadler, Claus (1); Auer,...",Lecture Notes in Computer Science (including s...,2013.0,English,10.1007/978-3-642-37996-3_5,The vast majority of the structured data of ou...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,An approach for automatically generating R2RML...,"Hazber, Mohamed A.G. (1); Li, Ruixuan (1); Xu,...",Communications in Computer and Information Sci...,2016.0,English,10.1007/978-981-10-2053-7_15,For integrating relational databases (RDBs) in...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Bag Semantics of DL-Lite with Functionality Ax...,"Cima, Gianluca (1); Nikolaou, Charalampos (2, ...",Lecture Notes in Computer Science (including s...,2019.0,English,10.1007/978-3-030-30793-6_8,Ontology-based data access (OBDA) is a popular...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Cancer data integration and querying with Gene...,"Shironoshita, E. Patrick (1); Jean-Mary, Yves ...",Lecture Notes in Computer Science (including s...,2012.0,English,10.1007/978-3-642-31040-9_6,"We present the GeneTegra system, an ontology-b...",1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,CASD: A Framework for Context Aware Service Di...,"Hussain, A. (1); MacCaull, W. (1); Lamo, Y. (2)",On the Move to Meaningful Internet Systems: OT...,2017.0,English,10.1007/978-3-319-55961-2_26,We present the architecture for a framework fo...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Could be worth to buy access,NaN
81,DAFO: An Ontological Database System with Face...,"Pankowski, T. (1); Bak, J. (1)",The Semantic Web: ESWC 2019 Satellite Events. ...,2019.0,English,10.1007/978-3-030-32327-1_30,We present an ontology-based data access provi...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,Data access in heterogeneous data sources usin...,"Hema, M.S. (1); Maheshprabhu, R. (1); Nageswar...",Communications in Computer and Information Sci...,2018.0,English,10.1007/978-981-10-7635-0_3,Data sourcing or integration is inevitable in ...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,Data Integration of Legacy ERP System Based on...,"Ma, Chuangtao (1)",Communications in Computer and Information Sci...,2019.0,English,10.1007/978-3-030-30278-8_52,To tackle the problem of low-efficiency integr...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,Database to ontology mapping patterns in RDB2O...,"erns, Krlis (1); Bmans, Guntars (1)",Communications in Computer and Information Sci...,2016.0,English,10.1007/978-3-319-40180-5_3,We describe the RDB2OWL Lite language for rela...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,Database to ontology mappings in RDB2OWL: Nota...,"Bumans, Guntars (1); erans, Karlis (1)",Frontiers in Artificial Intelligence and Appli...,2016.0,English,10.3233/978-1-61499-714-6-31,We review the RDB2OWL language for relational ...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,Effective Ontology-Based Data Integration,"Rosati, R. (1)",On the Move to Meaningful Internet Systems: OT...,2009.0,English,10.1007/978-3-642-05290-3_9,Summary form only given. The goal of data inte...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
117,Exploiting data dependencies with null values ...,"Amalfi, Maria (1)",Lecture Notes in Computer Science (including s...,2012.0,English,10.1007/978-3-642-34002-4_45,I present a novel methodology to automatically...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,Implementation of ontology extraction oriented...,"Cui, Shi Chao (1); Li, Ying (1); Wang, Yong Bi...",Advanced Materials Research,2013.0,English,10.4028/www.scientific.net/AMR.756-759.1489,"Ontology has be applied in many fields, such a...",1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,Integrating Heterogeneous Data Source Using On...,Jinpeng Wang (1); Jianjiang Lu (1); Yafei Zhan...,Journal of Software,2009.0,English,10.4304/jsw.4.8.843-850,Integrating data from multiple heterogeneous s...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,Iterative-based Relational Model to Ontology S...,"Wang F., Wang Y.-S., Zhao J.-F., Cui D.",Scopus,2019.0,English,10.13328/j.cnki.jos.005726,The rapid development of the semantic web make...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,Mediating RDF/S queries to relational and XML ...,"Koffina, I. (1); Serfiotis, G. (1); Christophi...",International Journal on Semantic Web and Info...,2006.0,English,10.4018/jswis.2006100103,Semantic Web (SW) technology aims to facilitat...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,OBDA constraints for effective query answering,"Hovland, Dag (1); Lanti, Davide (2); Rezk, Mar...",Lecture Notes in Computer Science (including s...,2016.0,English,10.1007/978-3-319-42019-6_18,In Ontology Based Data Access (OBDA) users pos...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
184,On Bounded-Memory Stream Data Processing with ...,"Özçep, Özgür Lütfü (1); Möller, Ralf (1)",Lecture Notes in Computer Science (including s...,2019.0,English,10.1007/978-3-030-22102-7_30,Various research groups of the description log...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,On the complexity of ontological reasoning und...,"Gottlob, Georg (1, 2, 3); Manna, Marco (1, 4);...",Lecture Notes in Computer Science (including s...,2012.0,English,10.1007/978-3-642-32589-2_1,Ontology-based data access is an emerging yet ...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,Ontological Based Approach of Integrating Big ...,"Ahmed J., Ahmed M.",Scopus,2020.0,English,10.1007/978-981-15-1420-3_38,Sematic Web is an extended form of the current...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,Ontology-based Data Access Using Views,"Sequeda, J.F. (1); Arenas, M. (2); Miranker, D...",Web Reasoning and Rule Systems. Proceedings of...,2012.0,English,10.1007/978-3-642-33203-6_29,"The OWL 2 QL profile, which is based on DL-Lit...",1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
251,RDF/RDFS-based relational database integration,"Chen, Huajun (1); Wu, Zhaohui (1); Wang, Heng ...",Proceedings - International Conference on Data...,2006.0,English,10.1109/ICDE.2006.127,We study the problem of answering queries thro...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,Research on ontology-based relational data int...,"Miao, Zhuang (1); Wang, Jingwu (2); Wang, Jinp...",Lecture Notes in Electrical Engineering,2011.0,English,10.1007/978-3-642-25553-3_41,"To integrate relational data semantically, sch...",1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
271,Semantic integration of patient data and quali...,"Dentler, K. (1); ten Teije, A. (1); Cornet, R....",Process Support and Knowledge Representation i...,2013.0,English,10.1007/978-3-642-36438-9_6,Electronic Health Records (EHRs) contain a wea...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,Semantic service-oriented architecture for ran...,"Hull, Richard (1); Bimson, Kent (2); Hyle, Ric...",Proceedings of SPIE - The International Societ...,2009.0,English,10.1117/12.818628,The Knowledge Management Framework (KMF) of th...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,SHRDIS: A Semantic-based Heterogeneous Relatio...,Jinpeng Wang (1); Yafei Zhang (1); Jianjiang L...,Advanced Materials Research,2010.0,English,10.4028/www.scientific.net/AMR.121-122.335,Integrating and querying data from heterogeneo...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,Systematical representation of RDF-to-relation...,"Runge, Lars (1); Schrage, Sebastian (1); May, ...",Lecture Notes in Computer Science (including s...,2018.0,English,10.1007/978-3-319-73805-5_33,This paper presents a representation for stori...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
312,Towards a language for representing and managi...,"Oro, Ermelinda (1, 2); Ruffolo, Massimo (1, 2)...",ICAART 2014 - Proceedings of the 6th Internati...,2014.0,English,10.5220/0004916906510656,The amount of data in our world has been explo...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,Towards large-scale probabilistic OBDA,"Schoenfisch, J. (1); Stuckenschmidt, H. (1)",Scalable Uncertainty Management 9th Internatio...,2015.0,English,10.1007/978-3-319-23540-0_8,Ontology-based Data Access has intensively bee...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
333,Using OWL ontology for reasoning about schema ...,Pankowski T.,Scopus,2012.0,English,10.3233/978-1-61499-105-2-430,We discuss the problem of creating a knowledge...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
335,Validation and Evaluation of the Mapping Proce...,"Benmahria, B. (1); Chaker, I. (1); Zahi, A. (1)",New Knowledge in Information Systems and Techn...,2019.0,English,10.1007/978-3-030-16181-1_32,"In this paper, we propose a generalized approa...",1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Articles à revérifier

In [21]:
selection_df[selection_df["Specific field"].notna() | selection_df["Based on"].notna()]

,Title,Authors,Source,Year,Language,Doi,Abstract,Not Available,Ad Hoc,Unrelated (Title),Unrelated (Abstract),Unrelated (First read),Small or informal ontologies,Proceedings,Survey,Kept After 2nd Filter,Specific field,Based on,Comments,Worth contacting the author
10,A Generalized Framework for Ontology-based Dat...,"Botoeva, E. (1); Calvanese, D. (1); Cogrel, B....",AI*IA 2018 - Advances in Artificial Intelligen...,2018.0,English,10.1007/978-3-030-03840-3_13,The database (DB) landscape has been significa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ontop,NaN,NaN
12,A heterogeneous geospatial data retrieval meth...,"Liu J., Liu H., Chen X., Guo X., Zhao Q., Li J...",Scopus,2021.0,English,10.3390/su13042005,Information resources have increased rapidly i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geospatial data,NaN,NaN,NaN
15,A Knowledge-Driven Geospatially Enabled Framew...,Liang Wu (1); Lei Xue (1); Chaoling Li (2); Xi...,ISPRS International Journal of Geo-Information,2017.0,English,10.3390/ijgi6060166,Geologic survey procedures accumulate large vo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geospatial data,NaN,NaN,NaN
23,A novel knowledge-based battery drain reducer ...,"Siddiqui I.F., Lee S.U.-J., Abbas A.",Scopus,2020.0,English,10.31209/2019.100000132,The issue of battery drainage in the gigantic ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IoT,NaN,NaN,NaN
28,A semantic approach to polystores,"Kharlamov, E.; Mailis, T.; Bereta, K.; Bilidas...",2016 IEEE International Conference on Big Data...,2016.0,English,10.1109/BigData.2016.7840898,In the database community Polystores is an eme...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ontop,Ontop implementation at Siemens,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,Towards a new generation of ontology based dat...,"Corcho O., Priyatna F., Chaves-Fraga D.",Scopus,2020.0,English,10.3233/SW-190384,Ontology Based Data Access (OBDA) refers to a ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Morph/MIRROR,NaN,NaN
316,Towards interoperability of spatial planning d...,"Janecka, Karel (1); Cerba, Otakar (1); Jedlick...",International Multidisciplinary Scientific Geo...,2013.0,English,10.5593/SGEM2013/BB2.V1/S11.051,The article describes the 5-steps harmonizatio...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geospatial data,NaN,NaN,NaN
321,Towards the next generation of the LinkedGeoDa...,"Ding, Linfang (1); Xiao, Guohui (1, 2); Pano, ...",Journal of Web Semantics,2021.0,English,10.1016/j.websem.2021.100662,"With the advancement of Semantic Technologies,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geospatial data,Ontop,NaN,NaN
326,Ultrawrap: SPARQL execution on relational data,"Sequeda, Juan F. (1); Miranker, Daniel P. (1)",Journal of Web Semantics,2013.0,English,10.1016/j.websem.2013.08.002,The Semantic Web's promise of web-wide data in...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ultrawrap,NaN,NaN
339,Web-based graphical querying of databases thro...,"Calvanese, Diego (1); Keet, C. Maria (1); Nutt...",Proceedings of the ACM Symposium on Applied Co...,2010.0,English,10.1145/1774088.1774384,Biological scientists have made large amounts ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ontop,NaN,NaN

#### Articles à sortir de covidence au premier filtre

In [19]:
selection_df[  selection_df["Unrelated (Title)"].notna() \
             | selection_df["Unrelated (Abstract)"].notna() \
               | selection_df["Proceedings"].notna() \
               | selection_df["Survey"].notna()]['Title']

0      “Just-in-time” generation of datasets by consi...
1      5th International Conference on Data Managemen...
3      A case study of integrating protein interactio...
7      A formal framework for coupling document spann...
19     A new approach to building ontologies from het...
                             ...
331    Using ontology databases for scalable query an...
334    Using the Linked Data for Building of the Prod...
336                VIG: Data scaling for OBDA benchmarks
338             VLog: A Rule Engine for Knowledge Graphs
340    WF2OML: A modeling language for mapping web fo...
Name: Title, Length: 182, dtype: object

In [21]:
selection_df[  selection_df["Not Available"].notna()]['Title']

2      A building method of virtual knowledge base ba...
5      A FCA-based approach to data integration in th...
8      A framework exchanging data from database reso...
9      A framework for analysis of ontology-based dat...
16     A Language for Ontology-based Metamodeling Sys...
33     A Semantic-Based EMRs Integration Framework fo...
34     A survey of approaches to representing SPARQL ...
36     A systematic mapping study of database resourc...
38     Accessing relational data on the web with Spar...
42     An approach for automatically generating R2RML...
62     Bag Semantics of DL-Lite with Functionality Ax...
68     Cancer data integration and querying with Gene...
70     CASD: A Framework for Context Aware Service Di...
81     DAFO: An Ontological Database System with Face...
83     Data access in heterogeneous data sources usin...
86     Data Integration of Legacy ERP System Based on...
92     Database to ontology mapping patterns in RDB2O...
93     Database to ontology mappings in RDB2OWL: Nota...
104            Effective Ontology-Based Data Integration
117    Exploiting data dependencies with null values ...
137    Implementation of ontology extraction oriented...
141    Integrating Heterogeneous Data Source Using On...
151    Iterative-based Relational Model to Ontology S...
169    Mediating RDF/S queries to relational and XML ...
178       OBDA constraints for effective query answering
184    On Bounded-Memory Stream Data Processing with ...
185    On the complexity of ontological reasoning und...
192    Ontological Based Approach of Integrating Big ...
205               Ontology-based Data Access Using Views
251       RDF/RDFS-based relational database integration
257    Research on ontology-based relational data int...
271    Semantic integration of patient data and quali...
276    Semantic service-oriented architecture for ran...
282    SHRDIS: A Semantic-based Heterogeneous Relatio...
297    Systematical representation of RDF-to-relation...
312    Towards a language for representing and managi...
317               Towards large-scale probabilistic OBDA
333    Using OWL ontology for reasoning about schema ...
335    Validation and Evaluation of the Mapping Proce...
Name: Title, dtype: object

#### Articles à sortir au 2e filtre en indiquant que c'est une méthode ad hoc

In [18]:
selection_df[selection_df["Based on"].notna()]["Title"]

10     A Generalized Framework for Ontology-based Dat...
28                     A semantic approach to polystores
50     An ontology-guided semantic data integration f...
53      Answering geosparql queries over relational data
54     Answering SPARQL Queries over Databases under ...
59     Automatic mapping rules and OWL ontology extra...
71     Chimera: A Bridge Between Big Data Analytics a...
75     Conceptual Schema Transformation in Ontology-B...
78         Controlled English Ontology-Based Data Access
79                Cost-driven ontology-based data access
87          Data integration through DL-LiteA ontologies
105       Efficient handling of SPARQL OPTIONAL for OBDA
106    Efficient Ontology-Based Data Integration with...
108          Efficient SPARQL-to-SQL with R2RML mappings
109    Engineering optimisations in query rewriting f...
110           English querying over ontologies: E-QuOnto
121    Formalisation and experiences of R2RML-based S...
130    Handling redundant processing in OBDA query ex...
134    How to stay ontop of your data: Databases, ont...
149    Interactive Pay as You Go Relational-to-Ontolo...
179            OBDA for log extraction in process mining
181    OBDA: Query rewriting or materialization? In p...
195    Ontology based access to exploration data at s...
196                Ontology Based Data Access in Statoil
202    Ontology-based data access and visualization o...
203    Ontology-based data access for extracting even...
206    Ontology-based data access with databases: A s...
208    Ontology-based data access: an application to ...
209       Ontology-based data access: Ontop of databases
212    Ontology-based governance of data-aware proces...
214    Ontology-based integration of cross-linked dat...
216    Ontology-driven extraction of event logs from ...
218                        Ontop of Geospatial Databases
219         Ontop-spatial: Ontop of geospatial databases
220    Ontop: answering SPARQL queries over relationa...
234    QODI: Query as context in automatic data integ...
236    Query processing for heterogeneous relational ...
237    Query transformation in ontology-based relatio...
238    Querying clinical data in HL7 RIM based relati...
241    Querying heterogeneous relational database usi...
247    R2RML by assertion: A semi-automatic tool for ...
255    Representing and querying norm states using te...
264    RODI: Benchmarking relational-to-ontology mapp...
265                 Rules and Ontology Based Data Access
303     The MASTRO system for ontology-based data access
313    Towards a new generation of ontology based dat...
321    Towards the next generation of the LinkedGeoDa...
326       Ultrawrap: SPARQL execution on relational data
339    Web-based graphical querying of databases thro...
Name: Title, dtype: object

#### Articles à sortir au 2e filtre (et donner une raison)

In [5]:
selection_df[selection_df["Unrelated (First read)"].notna() | selection_df["Small or informal ontologies"].notna() | selection_df["Based on"].notna() |  selection_df["Ad Hoc"].notna()]["Title"]

6      A federation model to support semantic SPARQL ...
10     A Generalized Framework for Ontology-based Dat...
11     A generic ontological network for Agri-food ex...
13     A hybrid approach of mapping relational databa...
14     A journey to Semantic Web query federation in ...
                             ...
327    Unlocking data for clinical research - The Ger...
330    Using a graph database for the ontology-based ...
332    Using ontology merging for the integration of ...
337     Visualizing semantic mapping based on view graph
339    Web-based graphical querying of databases thro...
Name: Title, Length: 94, dtype: object

In [23]:
selection_df[selection_df["Unrelated (First read)"].notna()]["Title"]

13     A hybrid approach of mapping relational databa...
24     A Preliminary Approach on Ontology-Based Visua...
73     Combination of DM and OBDA for ontology genera...
80     Crowd Sourced Semantic Enrichment (CroSSE) for...
120    Fast and Easy Mapping of Relational Data to RD...
132    HISMA: A human-machine iterative schema matchi...
148    Intensional first-order logic for P2P database...
152    KnowID: An Architecture for Efficient Knowledg...
162              Mapping Between Data Sources on the Web
172    MIRROR: Automatic R2RML mapping generation fro...
193    Ontology and database schema: What's the diffe...
222                   Optimizing SPARQL-to-SQL rewriting
275    Semantic Query for Integrated Heterogeneous Da...
305    The role of user requirements in data reposito...
315      Towards automating the creation of OBDA systems
325    Two-phase schema matching in real world relati...
332    Using ontology merging for the integration of ...
337     Visualizing semantic mapping based on view graph
Name: Title, dtype: object

#### Verify if any papers were given multiple marks
Some papers were identified as based on Ontop and were about Geospatial data or were not relevant.

In [6]:
selection_df[
    + selection_df["Not Available"].notna().astype(int) \
    + selection_df["Ad Hoc"].notna().astype(int) \
    + selection_df["Unrelated (Title)"].notna().astype(int) \
    + selection_df["Unrelated (Abstract)"] .notna().astype(int) \
    + selection_df["Unrelated (First read)"].notna().astype(int) \
    + selection_df["Small or informal ontologies"].notna().astype(int) \
    + selection_df["Proceedings"].notna().astype(int) \
    + selection_df["Survey"].notna().astype(int) \
    + selection_df["Specific field"].notna().astype(int) \
    + selection_df["Based on"].notna().astype(int) \
    + selection_df["Kept After 2nd Filter"].notna().astype(int) \
    > 1 \
]

,Title,Authors,Source,Year,Language,Doi,Abstract,Not Available,Ad Hoc,Unrelated (Title),Unrelated (Abstract),Unrelated (First read),Small or informal ontologies,Proceedings,Survey,Kept After 2nd Filter,Specific field,Based on,Comments,Worth contacting the author
53,Answering geosparql queries over relational data,"Bereta, K. (1); Xiao, G. (2); Koubarakis, M. (1)","International Archives of the Photogrammetry, ...",2017.0,English,10.5194/isprs-archives-XLII-4-W2-43-2017,In this paper we present the system Ontop-spat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geospatial data,Ontop,NaN,NaN
59,Automatic mapping rules and OWL ontology extra...,"Khazalah, F. (1); Malik, Z. (1); Rezgui, A. (2)",10th IEEE International Conference on Collabor...,2014.0,English,10.4108/icst.collaboratecom.2014.257493,Extracting Ontop mapping rules and OWL ontolog...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ontop,NaN,NaN
202,Ontology-based data access and visualization o...,"Bereta, Konstantina (1); Stamoulis, George (1)...",International Geoscience and Remote Sensing Sy...,2018.0,English,10.1109/IGARSS.2018.8518255,We present an Ontology-based data access techn...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geospatial data,Ontop,NaN,NaN
218,Ontop of Geospatial Databases,"Bereta, K. (1); Koubarakis, M. (1)",The Semantic Web - ISWC 2016. 15th Internation...,2016.0,English,10.1007/978-3-319-46523-4_3,We propose an OBDA approach for accessing geos...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geospatial data,Ontop,NaN,NaN
219,Ontop-spatial: Ontop of geospatial databases,"Bereta, K. (1); Guohui Xiao (2); Koubarakis, M...",Journal of Web Semantics,2019.0,English,10.1016/j.websem.2019.100514,"In this paper, we propose an OBDA approach for...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geospatial data,Ontop,NaN,NaN
220,Ontop: answering SPARQL queries over relationa...,"Calvanese, D. (1); Cogrel, B. (1); Komla-Ebri,...","Semantic Web - Interoperability, Usability, Ap...",2017.0,English,10.3233/SW-160217,"We present Ontop, an open-source Ontology-Base...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,Ontop,NaN,NaN
321,Towards the next generation of the LinkedGeoDa...,"Ding, Linfang (1); Xiao, Guohui (1, 2); Pano, ...",Journal of Web Semantics,2021.0,English,10.1016/j.websem.2021.100662,"With the advancement of Semantic Technologies,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Geospatial data,Ontop,NaN,NaN

In [14]:
# selection_df[selection_df["Title"].str.contains("morph-RDB")]
selection_df[selection_df["Authors"].notna() & selection_df["Authors"].str.contains("doan")]

Empty DataFrame
Columns: [Title, Authors, Source, Year, Language, Doi, Abstract, Not Available, Ad Hoc, Unrelated (Title), Unrelated (Abstract), Unrelated (First read), Small or informal ontologies, Proceedings, Survey, Kept After 2nd Filter, Specific field, Based on, Comments, Worth contacting the author]
Index: []

#### Verify if any papers not given any marks
A paper was written in Portuguese but was initially defined as English

In [127]:
selection_df[
    + selection_df["Not Available"].notna().astype(int)
    + selection_df["Ad Hoc"].notna().astype(int)
    + selection_df["Unrelated (Title)"].notna().astype(int)
    + selection_df["Unrelated (Abstract)"] .notna().astype(int)
    + selection_df["Unrelated (First read)"].notna().astype(int)
    + selection_df["Small or informal ontologies"].notna().astype(int)
    + selection_df["Proceedings"].notna().astype(int)
    + selection_df["Survey"].notna().astype(int)
    + selection_df["Specific field"].notna().astype(int)
    + selection_df["Based on"].notna().astype(int)
    + selection_df["Kept After 2nd Filter"].notna().astype(int)
    == 0 \
    ]

,Title,Authors,Source,Year,Language,Doi,Abstract,Not Available,Ad Hoc,Unrelated (Title),Unrelated (Abstract),Unrelated (First read),Small or informal ontologies,Proceedings,Survey,Kept After 2nd Filter,Specific field,Based on,Comments,Worth contacting the author
91,Database ontology-supported query for ubiquito...,"Maran V., Augustin I., Machado G.M., Lima J.C....",Scopus,2017.0,Portuguese,10.1145/3126858.3131575,One of the main research opportunities regardi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Read the final selection for verification and statistics

In [9]:
selection_2ndFilter_df = pandas.read_csv("selection_2ndFilter.csv")
selection_2ndFilter_df.set_index("Title")

selected = selection_2ndFilter_df.loc[selection_2ndFilter_df["Kept After 2nd Filter"] == 1.0].copy()
selected["Authors"] = selected["Authors"].fillna('')

semi_column_regex = r"([^;]+)(?:\(\d(?:\s*,\s*\d)*\));?\s*"
multiple_comma_regex = r"([^,(\d)]+),?\s*"
single_comma_regex = r"(?:([^, \n(\d)]+(?: [^, \n()\d]+)+ *), *([^, \n(\d)]+(?: [^, \n()\d]+)+ *))|([^\n(\d)]+)"
simple_regex = r"([^()\d]+)\s*(?:\s*\(\d(?:\s*,\s*\d)\))?\s*"

authors_alternative_names = {
    'Corcho, O.': ['Corcho, Oscar', 'Corcho O.' ],
    'Priyatna, F.': ['Priyatna F', 'Priyatna F.', 'Priyatna, Freddy'],
    'Sequeda, J.F.': ['Sequeda, J.F.', 'Sequeda, Juan', 'Sequeda, Juan F.'],
    'Wang, Y.': ['Wang Y.', 'Wang Y.-S.'],
    'Zhao, J.': ['Zhao J.', 'Zhao J.-F.'],
    'Pinkel, C.': ['Pinkel, C.', 'Pinkel, Christoph'],
    'Wang, J.': ['Jinpeng Wang', 'Wang, Jinpeng']
}

def update_author_name(author):
    author_deduplicated = author.strip()

    for name, alternatives in authors_alternative_names.items():
        if author_deduplicated in alternatives:
            author_deduplicated = name

    return author_deduplicated

def split_authors(authors_str):
    if ";" in authors_str:
        regex = semi_column_regex
    elif authors_str.count(',') > 1:
        regex = multiple_comma_regex
    elif authors_str.count(',') == 1:
        regex = single_comma_regex
    else:
        regex = simple_regex

    matchs = re.findall(regex, authors_str)
    if any(map(lambda x: type(x) == tuple, matchs)):
        return OrderedSet(update_author_name(y) for x in matchs for y in x if y.strip() != '')
    else:
        return OrderedSet(update_author_name(x) for x in matchs)

selected["Authors_list"] = list(map(split_authors, selected["Authors"].tolist()))

### Verify authors deduplication
We want to ensure that we don't seems to miss duplicate articles, we keep only the most relevant paper for each method

In [10]:
selected_authors = collections.Counter(chain.from_iterable(selected["Authors_list"].tolist()))
authors_in_multiple_papers = [x for x, count in selected_authors.items() if count > 1]

print("These papers might be duplicates:")
selected[selected["Authors_list"].map(lambda authors: any(author in authors for author in authors_in_multiple_papers))]

These papers might be duplicates:

Empty DataFrame
Columns: [Title, Authors, Source, Year, Language, Doi, Abstract, Not Available, Ad Hoc, Unrelated (Title), Unrelated (Abstract), Unrelated (First read), Small or informal ontologies, Proceedings, Survey, Kept After 2nd Filter, Specific field, Based on, Comments, Worth contacting the author, Authors_list]
Index: []

[0 rows x 21 columns]